// <auto-generated />
using System;
using Finance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance.Migrations.User
{
  [DbContext(typeof(UserContext))]
  [Migration("20240704111309_CreateUserTable")]
  partial class CreateUserTable
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

      modelBuilder.Entity("Finance.Models.User", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("TEXT");

            b.Property<string>("Email")
                      .IsRequired()
                      .HasColumnType("TEXT");

            b.Property<string>("FirstName")
                      .IsRequired()
                      .HasColumnType("TEXT");

            b.Property<string>("LastName")
                      .IsRequired()
                      .HasColumnType("TEXT");

            b.Property<string>("Password")
                      .IsRequired()
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("Users");
          });
#pragma warning restore 612, 618
    }
  }
}
